services:
  postgres:
    container_name: postgres
    image: postgres:18
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - my_network

  rustfs:
    container_name: rustfs
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
    volumes:
      - rustfs_data:/data
    networks:
      - my_network
    command:
      ["--access-key", "rustfsadmin", "--secret-key", "rustfsadmin", "/data"]

  # drizzle-gate:
  #   image: ghcr.io/drizzle-team/gateway:latest
  #   container_name: drizzle-gate
  #   restart: always
  #   ports:
  #     - "4983:4983"
  #   environment:
  #     - PORT=4983
  #     - MASTERPASS=ozaki
  #   volumes:
  #     - drizzle:/app
  #   networks:
  #     - my_network

  lightpanda:
    container_name: lightpanda
    image: lightpanda/browser:nightly
    ports:
      - "127.0.0.1:9223:9222"
    networks:
      - my_network

  otelite:
    build: .
    ports:
      - "4317:4317"
      - "4318:4318"
      - "4000:3000"
    volumes:
      - otelite_data:/home/ozaki/.local/share/otelite

networks:
  my_network:
    driver: bridge

volumes:
  pgdata:
  rustfs_data:
  otelite_data:
  # drizzle:
