blockExoticSubdeps: true

minimumReleaseAge: 1000

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
trustPolicyExclude:
  - "tinyexec"
  - "@effect/vitest@4.0.0-beta.98"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: true
  workerd: true
configDependencies:
  "@pnpm/pacquet": 0.2.14
overrides:
  "kysely": "^0.29.2"
  "better-auth": "1.6.14"
patchedDependencies:
  "@tanstack/react-db@0.1.86": patches/@tanstack__react-db.patch
