/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as AccountRouteImport } from './routes/account'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as UsersIdRouteImport } from './routes/users.$id'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as PostsTagsTagRouteImport } from './routes/posts/tags/$tag'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiVideoStreamIdRouteImport } from './routes/api/video/stream.$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const PostsTagsTagRoute = PostsTagsTagRouteImport.update({
  id: '/posts/tags/$tag',
  path: '/posts/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoStreamIdRoute = ApiVideoStreamIdRouteImport.update({
  id: '/api/video/stream/$id',
  path: '/api/video/stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/convert': typeof ConvertRoute
  '/upload': typeof UploadRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$id': typeof UsersIdRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/posts/tags/$tag': typeof PostsTagsTagRoute
  '/api/video/stream/$id': typeof ApiVideoStreamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/convert': typeof ConvertRoute
  '/upload': typeof UploadRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$id': typeof UsersIdRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/posts/tags/$tag': typeof PostsTagsTagRoute
  '/api/video/stream/$id': typeof ApiVideoStreamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/convert': typeof ConvertRoute
  '/upload': typeof UploadRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$id': typeof UsersIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/posts/tags/$tag': typeof PostsTagsTagRoute
  '/api/video/stream/$id': typeof ApiVideoStreamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/convert'
    | '/upload'
    | '/login'
    | '/signup'
    | '/posts/$postId'
    | '/users/$id'
    | '/posts'
    | '/users'
    | '/api/auth/$'
    | '/posts/tags/$tag'
    | '/api/video/stream/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/convert'
    | '/upload'
    | '/login'
    | '/signup'
    | '/posts/$postId'
    | '/users/$id'
    | '/posts'
    | '/users'
    | '/api/auth/$'
    | '/posts/tags/$tag'
    | '/api/video/stream/$id'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/account'
    | '/convert'
    | '/upload'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/posts/$postId'
    | '/users/$id'
    | '/posts/'
    | '/users/'
    | '/api/auth/$'
    | '/posts/tags/$tag'
    | '/api/video/stream/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  ConvertRoute: typeof ConvertRoute
  UploadRoute: typeof UploadRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  UsersIdRoute: typeof UsersIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PostsTagsTagRoute: typeof PostsTagsTagRoute
  ApiVideoStreamIdRoute: typeof ApiVideoStreamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/posts/tags/$tag': {
      id: '/posts/tags/$tag'
      path: '/posts/tags/$tag'
      fullPath: '/posts/tags/$tag'
      preLoaderRoute: typeof PostsTagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/stream/$id': {
      id: '/api/video/stream/$id'
      path: '/api/video/stream/$id'
      fullPath: '/api/video/stream/$id'
      preLoaderRoute: typeof ApiVideoStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  ConvertRoute: ConvertRoute,
  UploadRoute: UploadRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  UsersIdRoute: UsersIdRoute,
  PostsIndexRoute: PostsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PostsTagsTagRoute: PostsTagsTagRoute,
  ApiVideoStreamIdRoute: ApiVideoStreamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
